In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\cntej\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\cntej\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.1.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

LOADING THE DATASET

In [3]:
import pandas as pd

# Paths to the Excel file
file_path = "C:/Users/cntej/Downloads/Canada_Hosp1_COVID_InpatientData.xlsx"

# Read specific sheets
df1 = pd.read_excel(file_path, sheet_name='Data-at-admission')
df2 = pd.read_excel(file_path, sheet_name='Days-breakdown')
df3 = pd.read_excel(file_path, sheet_name='Hospital-length-of-stay')

In [4]:
df1.head()

,id,reason_for_admission,age,sex,ethnicity,ethnicity_other,height,weight,comorbidities,comorbidities_other,...,pao2,pao2_fio2,ph,high_senstivity_cardiac_troponin,esr,inr,ferritin,d_dimer,crp,hs_crp
0,1,Fever [R50.9],74,Male,"""[]""",NaN,NaN,NaN,"""[\""Hypertension\"",\""Diabetes\"",\""Other\""]""","GERD (gastroesophageal reflux disease), Dement...",...,NaN,NaN,NaN,NaN,NaN,1.1,NaN,NaN,223.0,NaN
1,2,Pneumonia [J18.9],61,Female,"""[]""",NaN,154.9,73.6,"""[\""Hypertension\"",\""Other\""]""","Closed fracture of fifth metatarsal bone, Dive...",...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2354,95.6,NaN
2,3,Pneumonia [J18.9],58,Female,"""[]""",NaN,NaN,NaN,"""[\""Hypertension\""]""",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Suspected COVID-19 virus infection [U07.2],94,Male,"""[]""",NaN,182.8,66.2,"""[\""Hypertension\"",\""Other\""]""","Parkinson's Disease, Back pain, Benign Prostat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,"Febrile respiratory illness [J98.9, R50.9]",91,Male,"""[]""",NaN,NaN,NaN,"""[\""Chronic cardiac disease (not hypertension)...","TAVI, Atrial fibrillation, Gastric Reflux, Pac...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df1.shape)

(508, 55)

PREPROCESSING THE DATA-AT-ADMISSION DATASET

DROPPING UNWANTED COLUMNS

In [6]:
df1.columns

Index(['id', 'reason_for_admission', 'age', 'sex', 'ethnicity',
       'ethnicity_other', 'height', 'weight', 'comorbidities',
       'comorbidities_other', 'received_covid_vaccine', 'covid_vaccine',
       'medications', 'smoking_history', 'year_they_quit',
       'previous_er_visit_within_14_days', 'admission_disposition',
       'systolic_blood_pressure', 'diastolic_blood_pressure', 'heart_rate',
       'respiratory_rate', 'oxygen_saturation', 'temperature', 'motor',
       'verbal', 'eye', 'intubated', 'wbc', 'rbc', 'hemoglobin', 'hematocrit',
       'mcv', 'mch', 'mchc', 'rdw', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'serum_creatinine', 'sodium', 'potassium',
       'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2', 'ph',
       'high_senstivity_cardiac_troponin', 'esr', 'inr', 'ferritin', 'd_dimer',
       'crp', 'hs_crp'],
      dtype='object')

In [7]:

df1 = df1.drop(['reason_for_admission','ethnicity','ethnicity_other','comorbidities_other', 'received_covid_vaccine', 'covid_vaccine',
       'medications', 'smoking_history', 'year_they_quit',
       'previous_er_visit_within_14_days', 'admission_disposition'], axis=1)

df1.head()

,id,age,sex,height,weight,comorbidities,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,...,pao2,pao2_fio2,ph,high_senstivity_cardiac_troponin,esr,inr,ferritin,d_dimer,crp,hs_crp
0,1,74,Male,NaN,NaN,"""[\""Hypertension\"",\""Diabetes\"",\""Other\""]""",99,62,85,20,...,NaN,NaN,NaN,NaN,NaN,1.1,NaN,NaN,223.0,NaN
1,2,61,Female,154.9,73.6,"""[\""Hypertension\"",\""Other\""]""",122,77,93,36,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2354,95.6,NaN
2,3,58,Female,NaN,NaN,"""[\""Hypertension\""]""",109,72,73,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,94,Male,182.8,66.2,"""[\""Hypertension\"",\""Other\""]""",165,71,92,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,91,Male,NaN,NaN,"""[\""Chronic cardiac disease (not hypertension)...",131,76,60,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df1.describe()

,id,age,height,weight,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,oxygen_saturation,temperature,...,lactate,pao2,pao2_fio2,ph,high_senstivity_cardiac_troponin,esr,inr,ferritin,crp,hs_crp
count,508.000000,508.000000,272.000000,358.000000,508.000000,508.000000,508.000000,508.000000,508.000000,508.000000,...,362.000000,32.000000,23.0,32.000000,0.0,5.000000,315.000000,20.000000,142.000000,0.0
mean,260.877953,66.027559,166.911029,80.265922,129.362205,75.566929,97.397638,24.901575,93.100394,37.768110,...,2.330663,77.906250,1.5,7.347500,NaN,61.800000,1.159365,1003.750000,109.128873,NaN
std,150.701859,16.394160,10.961776,21.810799,22.051194,12.851352,17.513347,7.170656,6.102006,0.963806,...,1.245724,16.471597,0.0,0.130853,NaN,34.215494,0.676116,1575.314634,74.861851,NaN
min,1.000000,19.000000,125.000000,27.700000,85.000000,22.000000,41.000000,12.000000,47.000000,35.500000,...,0.600000,53.000000,1.5,7.000000,NaN,28.000000,0.900000,122.000000,3.000000,NaN
25%,130.500000,55.750000,159.000000,65.800000,115.000000,68.000000,86.000000,20.000000,92.000000,37.000000,...,1.600000,76.000000,1.5,7.302500,NaN,32.000000,1.000000,249.500000,52.975000,NaN
50%,262.500000,66.000000,167.600000,76.700000,127.000000,75.000000,98.000000,24.000000,94.000000,37.700000,...,2.050000,76.000000,1.5,7.395000,NaN,55.000000,1.000000,586.500000,93.150000,NaN
75%,391.250000,78.000000,175.000000,89.800000,143.000000,83.000000,109.000000,28.000000,96.000000,38.500000,...,2.700000,76.000000,1.5,7.440000,NaN,89.000000,1.100000,994.250000,158.750000,NaN
max,522.000000,100.000000,198.000000,199.600000,227.000000,145.000000,161.000000,59.000000,100.000000,40.500000,...,13.800000,155.000000,1.5,7.490000,NaN,105.000000,8.900000,7319.000000,371.000000,NaN

CHECKING FOR MISSING VALUES

In [9]:
df1.isnull().sum()

id                                    0
age                                   0
sex                                   0
height                              236
weight                              150
comorbidities                         0
systolic_blood_pressure               0
diastolic_blood_pressure              0
heart_rate                            0
respiratory_rate                      0
oxygen_saturation                     0
temperature                           0
motor                                 2
verbal                                2
eye                                   2
intubated                             0
wbc                                   2
rbc                                   2
hemoglobin                            2
hematocrit                            2
mcv                                   2
mch                                   2
mchc                                  2
rdw                                   2
platelet_count                        2
aptt_aptr                           220
pt                                  193
alt                                 105
ast                                 105
serum_creatinine                      2
sodium                                2
potassium                             2
total_serum_bilirubin               105
lactate                             146
pao2                                476
pao2_fio2                           485
ph                                  476
high_senstivity_cardiac_troponin    508
esr                                 503
inr                                 193
ferritin                            488
d_dimer                             256
crp                                 366
hs_crp                              508
dtype: int64

HANDLING NUMERICAL DATA

IMPUTING NUMERICAL VALUES WITH MEDIAN

In [10]:

numerical_columns = ['height','weight','motor', 'verbal', 'eye', 'wbc', 'rbc', 'hemoglobin', 'hematocrit', 
                     'mcv', 'mch', 'mchc', 'rdw', 'platelet_count', 'alt', 
                     'ast', 'serum_creatinine', 'sodium', 'potassium', 
                     'total_serum_bilirubin', 'lactate']


for col in numerical_columns:
    df1[col].fillna(df1[col].median(), inplace=True)

print("Missing values after imputing numerical columns with median:")
print(df1.isnull().sum())

Missing values after imputing numerical columns with median:
id                                    0
age                                   0
sex                                   0
height                                0
weight                                0
comorbidities                         0
systolic_blood_pressure               0
diastolic_blood_pressure              0
heart_rate                            0
respiratory_rate                      0
oxygen_saturation                     0
temperature                           0
motor                                 0
verbal                                0
eye                                   0
intubated                             0
wbc                                   0
rbc                                   0
hemoglobin                            0
hematocrit                            0
mcv                                   0
mch                                   0
mchc                                  0
rdw                                   0
platelet_count                        0
aptt_aptr                           220
pt                                  193
alt                                   0
ast                                   0
serum_creatinine                      0
sodium                                0
potassium                             0
total_serum_bilirubin                 0
lactate                               0
pao2                                476
pao2_fio2                           485
ph                                  476
high_senstivity_cardiac_troponin    508
esr                                 503
inr                                 193
ferritin                            488
d_dimer                             256
crp                                 366
hs_crp                              508
dtype: int64

Dropping columns with 100% missing values

In [11]:
print(df1.columns)

Index(['id', 'age', 'sex', 'height', 'weight', 'comorbidities',
       'systolic_blood_pressure', 'diastolic_blood_pressure', 'heart_rate',
       'respiratory_rate', 'oxygen_saturation', 'temperature', 'motor',
       'verbal', 'eye', 'intubated', 'wbc', 'rbc', 'hemoglobin', 'hematocrit',
       'mcv', 'mch', 'mchc', 'rdw', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'serum_creatinine', 'sodium', 'potassium',
       'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2', 'ph',
       'high_senstivity_cardiac_troponin', 'esr', 'inr', 'ferritin', 'd_dimer',
       'crp', 'hs_crp'],
      dtype='object')

In [12]:

df1.drop(['high_senstivity_cardiac_troponin', 'hs_crp'], axis=1, inplace=True)

print(df1.columns)

Index(['id', 'age', 'sex', 'height', 'weight', 'comorbidities',
       'systolic_blood_pressure', 'diastolic_blood_pressure', 'heart_rate',
       'respiratory_rate', 'oxygen_saturation', 'temperature', 'motor',
       'verbal', 'eye', 'intubated', 'wbc', 'rbc', 'hemoglobin', 'hematocrit',
       'mcv', 'mch', 'mchc', 'rdw', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'serum_creatinine', 'sodium', 'potassium',
       'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2', 'ph', 'esr',
       'inr', 'ferritin', 'd_dimer', 'crp'],
      dtype='object')

In [13]:
df1.isnull().sum()

id                            0
age                           0
sex                           0
height                        0
weight                        0
comorbidities                 0
systolic_blood_pressure       0
diastolic_blood_pressure      0
heart_rate                    0
respiratory_rate              0
oxygen_saturation             0
temperature                   0
motor                         0
verbal                        0
eye                           0
intubated                     0
wbc                           0
rbc                           0
hemoglobin                    0
hematocrit                    0
mcv                           0
mch                           0
mchc                          0
rdw                           0
platelet_count                0
aptt_aptr                   220
pt                          193
alt                           0
ast                           0
serum_creatinine              0
sodium                        0
potassium                     0
total_serum_bilirubin         0
lactate                       0
pao2                        476
pao2_fio2                   485
ph                          476
esr                         503
inr                         193
ferritin                    488
d_dimer                     256
crp                         366
dtype: int64

HANDLING CATEGORICAL DATA

In [14]:
import ast

# Function to safely convert strings to lists
def convert_to_list(value):
    try:
        # Checking if the value is a string and not already a list
        if isinstance(value, str):
            return ast.literal_eval(value)
        else:
            return value 
    except (ValueError, SyntaxError):
        return value

# Applying the conversion function to the 'comorbidities' column
df1['comorbidities'] = df1['comorbidities'].apply(convert_to_list)

print(df1['comorbidities'].head(10))

0                  ["Hypertension","Diabetes","Other"]
1                             ["Hypertension","Other"]
2                                     ["Hypertension"]
3                             ["Hypertension","Other"]
4    ["Chronic cardiac disease (not hypertension)",...
5                                     ["Hypertension"]
6                                                   []
7    ["Chronic cardiac disease (not hypertension)",...
8                  ["Hypertension","Diabetes","Other"]
9                             ["Hypertension","Other"]
Name: comorbidities, dtype: object

In [15]:
# checking for empty lists
empty_lists_count = df1['comorbidities'].apply(lambda x: len(x) == 0).sum()

print(f"Number of empty lists in comorbidities: {empty_lists_count}")

Number of empty lists in comorbidities: 0

In [16]:
# Replacing empty lists with 'No Comorbidities'
df1['comorbidities'] = df1['comorbidities'].apply(lambda x: ['No Comorbidities'] if len(x) == 0 else x)
empty_lists_count = df1['comorbidities'].apply(lambda x: len(x) == 0).sum()

print(f"Number of empty lists in comorbidities: {empty_lists_count}")

Number of empty lists in comorbidities: 0

ENCODING CATEGORICAL VARIABLES

In [17]:

from sklearn.preprocessing import MultiLabelBinarizer
print(type(df1['comorbidities'].iloc[0]))
def safe_eval(val):
    if isinstance(val, str):
        return eval(val)
    return val
df1['comorbidities'] = df1['comorbidities'].apply(safe_eval)
mlb = MultiLabelBinarizer()
comorbidities_encoded = mlb.fit_transform(df1['comorbidities'])
comorbidities_df = pd.DataFrame(comorbidities_encoded, columns=mlb.classes_)
print(comorbidities_df.head())

<class 'str'>
   Asthma  Cancer [active only]  Chronic cardiac disease (not hypertension)  \
0       0                     0                                           0
1       0                     0                                           0
2       0                     0                                           0
3       0                     0                                           0
4       0                     0                                           1

   Chronic neurological disorder  Chronic pulmonary (lung) disease  \
0                              0                                 0
1                              0                                 0
2                              0                                 0
3                              0                                 0
4                              0                                 0

   Chronic renal  Dementia [any etiology]  Diabetes  Hematological  \
0              0                        0         1              0
1              0                        0         0              0
2              0                        0         0              0
3              0                        0         0              0
4              0                        0         1              0

   History of cancer [now in remission]  Hypertension  Kidney disease  \
0                                     0             1               0
1                                     0             1               0
2                                     0             1               0
3                                     0             1               0
4                                     0             1               0

   Liver disease  Obesity  Other  Pregnancy  Rheumatologic disorder  Stroke
0              0        0      1          0                       0       0
1              0        0      1          0                       0       0
2              0        0      0          0                       0       0
3              0        0      1          0                       0       0
4              0        0      1          0                       0       0

Concatenating the comorbidities_d to df1.

In [18]:
# Concatenate the original df1 with the new comorbidities_df
df1 = pd.concat([df1, comorbidities_df], axis=1)
df1.drop(columns=['comorbidities'], inplace=True)
print(df1.head())

   id  age     sex  height  weight  systolic_blood_pressure  \
0   1   74    Male   167.6    76.7                       99
1   2   61  Female   154.9    73.6                      122
2   3   58  Female   167.6    76.7                      109
3   4   94    Male   182.8    66.2                      165
4   5   91    Male   167.6    76.7                      131

   diastolic_blood_pressure  heart_rate  respiratory_rate  oxygen_saturation  \
0                        62          85                20                 93
1                        77          93                36                 88
2                        72          73                24                 91
3                        71          92                16                 96
4                        76          60                18                 95

   ...  Hematological  History of cancer [now in remission]  Hypertension  \
0  ...              0                                     0             1
1  ...              0                                     0             1
2  ...              0                                     0             1
3  ...              0                                     0             1
4  ...              0                                     0             1

   Kidney disease Liver disease  Obesity  Other  Pregnancy  \
0               0             0        0      1          0
1               0             0        0      1          0
2               0             0        0      0          0
3               0             0        0      1          0
4               0             0        0      1          0

   Rheumatologic disorder  Stroke
0                       0       0
1                       0       0
2                       0       0
3                       0       0
4                       0       0

[5 rows x 59 columns]

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df1['SEX'] = le.fit_transform(df1['sex'].str.strip())  # Removing any leading/trailing spaces

df1['INTUBATED'] = le.fit_transform(df1['intubated'].str.strip())  # Assuming 'intubated' is categorical

print(df1[['sex', 'SEX', 'intubated', 'INTUBATED']].head())

df1.drop(columns=['sex', 'intubated'], inplace=True)

      sex  SEX intubated  INTUBATED
0    Male    1        No          0
1  Female    0        No          0
2  Female    0        No          0
3    Male    1        No          0
4    Male    1        No          0

In [20]:
df1.head()

,id,age,height,weight,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,oxygen_saturation,temperature,...,Hypertension,Kidney disease,Liver disease,Obesity,Other,Pregnancy,Rheumatologic disorder,Stroke,SEX,INTUBATED
0,1,74,167.6,76.7,99,62,85,20,93,37.5,...,1,0,0,0,1,0,0,0,1,0
1,2,61,154.9,73.6,122,77,93,36,88,38.0,...,1,0,0,0,1,0,0,0,0,0
2,3,58,167.6,76.7,109,72,73,24,91,38.3,...,1,0,0,0,0,0,0,0,0,0
3,4,94,182.8,66.2,165,71,92,16,96,37.5,...,1,0,0,0,1,0,0,0,1,0
4,5,91,167.6,76.7,131,76,60,18,95,38.2,...,1,0,0,0,1,0,0,0,1,0

In [21]:
df1.shape

(508, 59)

PRE PROCESSING THE HOSPITAL-LENGTH-OF-STAY

CHECKING FOR NULL VALUES AFTER PREPROCESSING

In [22]:
df3.isnull().sum()

id                                                    0
parent_id                                             0
did_the_patient_expire_in_hospital                    0
reason_for_death                                    433
days_in_hospital_prior_to_expiration                419
hospital_length_of_stay                               0
icu_length_of_stay                                  392
days_in_hospital_prior_to_icu_admission             419
time_on_mechanical_ventilation                      232
days_in_hospital_prior_to_mechanical_ventilation    447
days_to_first_covid19_test_negative                 451
dtype: int64

In [23]:

df3 = df3[['hospital_length_of_stay', 'parent_id']]

print(df3.head())

   hospital_length_of_stay  parent_id
0                       21          1
1                        5          2
2                        7          3
3                        9          4
4                        9          5

Using KNN to impute columns with more than 50% null values

Esuring all columns are numerical before applying KNN

In [24]:
columns_to_imputeknn = ['aptt_aptr','pt','pao2','pao2_fio2','ph','esr','inr','ferritin','d_dimer','crp']      

df1[columns_to_imputeknn] = df1[columns_to_imputeknn].apply(pd.to_numeric, errors='coerce')
print(df1[columns_to_imputeknn].dtypes)

aptt_aptr    float64
pt           float64
pao2         float64
pao2_fio2    float64
ph           float64
esr          float64
inr          float64
ferritin     float64
d_dimer      float64
crp          float64
dtype: object

In [25]:
from sklearn.impute import KNNImputer


knn_imputer = KNNImputer(n_neighbors=5)

# ApplyING KNN imputation to the relevant columns
df1[columns_to_imputeknn] = knn_imputer.fit_transform(df1[columns_to_imputeknn])

print(df1.isnull().sum())

id                                            0
age                                           0
height                                        0
weight                                        0
systolic_blood_pressure                       0
diastolic_blood_pressure                      0
heart_rate                                    0
respiratory_rate                              0
oxygen_saturation                             0
temperature                                   0
motor                                         0
verbal                                        0
eye                                           0
wbc                                           0
rbc                                           0
hemoglobin                                    0
hematocrit                                    0
mcv                                           0
mch                                           0
mchc                                          0
rdw                                           0
platelet_count                                0
aptt_aptr                                     0
pt                                            0
alt                                           0
ast                                           0
serum_creatinine                              0
sodium                                        0
potassium                                     0
total_serum_bilirubin                         0
lactate                                       0
pao2                                          0
pao2_fio2                                     0
ph                                            0
esr                                           0
inr                                           0
ferritin                                      0
d_dimer                                       0
crp                                           0
Asthma                                        0
Cancer [active only]                          0
Chronic cardiac disease (not hypertension)    0
Chronic neurological disorder                 0
Chronic pulmonary (lung) disease              0
Chronic renal                                 0
Dementia [any etiology]                       0
Diabetes                                      0
Hematological                                 0
History of cancer [now in remission]          0
Hypertension                                  0
Kidney disease                                0
Liver disease                                 0
Obesity                                       0
Other                                         0
Pregnancy                                     0
Rheumatologic disorder                        0
Stroke                                        0
SEX                                           0
INTUBATED                                     0
dtype: int64

Checking for Numerical columns that needs to be normalised

In [26]:
import pandas as pd

pd.set_option('display.max_columns', None)

print(df1.describe())

               id         age      height      weight  \
count  508.000000  508.000000  508.000000  508.000000
mean   260.877953   66.027559  167.231102   79.212992
std    150.701859   16.394160    8.021604   18.374419
min      1.000000   19.000000  125.000000   27.700000
25%    130.500000   55.750000  166.000000   70.700000
50%    262.500000   66.000000  167.600000   76.700000
75%    391.250000   78.000000  168.000000   82.225000
max    522.000000  100.000000  198.000000  199.600000

       systolic_blood_pressure  diastolic_blood_pressure  heart_rate  \
count               508.000000                508.000000  508.000000
mean                129.362205                 75.566929   97.397638
std                  22.051194                 12.851352   17.513347
min                  85.000000                 22.000000   41.000000
25%                 115.000000                 68.000000   86.000000
50%                 127.000000                 75.000000   98.000000
75%                 143.000000                 83.000000  109.000000
max                 227.000000                145.000000  161.000000

       respiratory_rate  oxygen_saturation  temperature       motor  \
count        508.000000         508.000000   508.000000  508.000000
mean          24.901575          93.100394    37.768110    5.913386
std            7.170656           6.102006     0.963806    0.461942
min           12.000000          47.000000    35.500000    1.000000
25%           20.000000          92.000000    37.000000    6.000000
50%           24.000000          94.000000    37.700000    6.000000
75%           28.000000          96.000000    38.500000    6.000000
max           59.000000         100.000000    40.500000    6.000000

           verbal         eye         wbc         rbc  hemoglobin  hematocrit  \
count  508.000000  508.000000  508.000000  508.000000  508.000000  508.000000
mean     4.769685    3.944882    8.030118    4.624646  129.879921    0.395063
std      0.718937    0.315468    3.737171    0.718202   17.980686    0.051355
min      1.000000    1.000000    2.000000    2.780000   74.000000    0.230000
25%      5.000000    4.000000    5.500000    4.157500  119.000000    0.362000
50%      5.000000    4.000000    7.400000    4.605000  131.000000    0.397000
75%      5.000000    4.000000    9.700000    5.050000  142.000000    0.430000
max      5.000000    4.000000   33.400000    8.210000  180.000000    0.552000

              mcv         mch        mchc         rdw  platelet_count  \
count  508.000000  508.000000  508.000000  508.000000      508.000000
mean    86.028740   28.290748  328.586614   13.971457      230.868110
std      7.364428    2.820678   13.466680    1.882270       97.826782
min     56.700000   17.300000  272.000000   10.300000       19.000000
25%     82.600000   27.100000  319.000000   12.800000      163.750000
50%     86.500000   28.700000  330.000000   13.550000      214.000000
75%     90.300000   30.000000  338.000000   14.600000      276.000000
max    112.200000   38.200000  382.000000   24.800000      671.000000

        aptt_aptr          pt         alt          ast  serum_creatinine  \
count  508.000000  508.000000  508.000000   508.000000        508.000000
mean    30.889526   14.620819   48.509843    58.423228        114.700787
std      5.258803    4.309857   45.729307    70.159357         91.841564
min     20.000000   11.700000    6.000000    11.000000         30.000000
25%     28.000000   13.200000   29.000000    37.000000         76.000000
50%     30.912892   14.000000   38.000000    47.000000         95.000000
75%     32.000000   14.618095   52.000000    61.000000        121.000000
max     76.000000   72.600000  586.000000  1307.000000       1179.000000

          sodium   potassium  total_serum_bilirubin     lactate        pao2  \
count  508.00000  508.000000             508.000000  508.000000  508.000000
mean   135.32874    3.885827              10.293307    2.250000   74.527313
std      5.18344    0.526905               5.115876    1.058827    6.371877
min    112.00000    2.100000               3.000000    0.600000   53.000000
25%    133.00000    3.500000               8.000000    1.800000   69.400000
50%    135.00000    3.900000               9.000000    2.050000   74.200000
75%    138.00000    4.200000              11.000000    2.400000   77.906250
max    161.00000    6.300000              40.000000   13.800000  155.000000

       pao2_fio2          ph         esr         inr     ferritin  \
count      508.0  508.000000  508.000000  508.000000   508.000000
mean         1.5    7.349524   61.800000    1.159079  1017.581201
std          0.0    0.048162    3.039127    0.540565   579.528519
min          1.5    7.000000   28.000000    0.900000   122.000000
25%          1.5    7.330000   61.800000    1.000000   714.400000
50%          1.5    7.343000   61.800000    1.100000   865.800000
75%          1.5    7.355000   61.800000    1.159365  1003.750000
max          1.5    7.490000  105.000000    8.900000  7319.000000

           d_dimer         crp      Asthma  Cancer [active only]  \
count   508.000000  508.000000  508.000000            508.000000
mean   1306.819458  117.414760    0.106299              0.053150
std     594.826462   47.341869    0.308524              0.224553
min     277.000000    3.000000    0.000000              0.000000
25%     871.250000   97.410000    0.000000              0.000000
50%    1289.987705  109.128873    0.000000              0.000000
75%    1545.750000  141.770000    0.000000              0.000000
max    3750.000000  371.000000    1.000000              1.000000

       Chronic cardiac disease (not hypertension)  \
count                                  508.000000
mean                                     0.173228
std                                      0.378818
min                                      0.000000
25%                                      0.000000
50%                                      0.000000
75%                                      0.000000
max                                      1.000000

       Chronic neurological disorder  Chronic pulmonary (lung) disease  \
count                     508.000000                        508.000000
mean                        0.005906                          0.055118
std                         0.076696                          0.228436
min                         0.000000                          0.000000
25%                         0.000000                          0.000000
50%                         0.000000                          0.000000
75%                         0.000000                          0.000000
max                         1.000000                          1.000000

       Chronic renal  Dementia [any etiology]    Diabetes  Hematological  \
count     508.000000               508.000000  508.000000     508.000000
mean        0.078740                 0.070866    0.344488       0.009843
std         0.269598                 0.256854    0.475670       0.098817
min         0.000000                 0.000000    0.000000       0.000000
25%         0.000000                 0.000000    0.000000       0.000000
50%         0.000000                 0.000000    0.000000       0.000000
75%         0.000000                 0.000000    1.000000       0.000000
max         1.000000                 1.000000    1.000000       1.000000

       History of cancer [now in remission]  Hypertension  Kidney disease  \
count                            508.000000    508.000000      508.000000
mean                               0.039370      0.610236        0.029528
std                                0.194666      0.488177        0.169447
min                                0.000000      0.000000        0.000000
25%                                0.000000      0.000000        0.000000
50%                                0.000000      1.000000        0.000000
75%                                0.000000      1.000000        0.000000
max                                1.000000      1.000000        1.000000

       Liver disease     Obesity       Other   Pregnancy  \
count     508.000000  508.000000  508.000000  508.000000
mean        0.005906    0.061024    0.797244    0.007874
std         0.076696    0.239610    0.402448    0.088473
min         0.000000    0.000000    0.000000    0.000000
25%         0.000000    0.000000    1.000000    0.000000
50%         0.000000    0.000000    1.000000    0.000000
75%         0.000000    0.000000    1.000000    0.000000
max         1.000000    1.000000    1.000000    1.000000

       Rheumatologic disorder      Stroke         SEX   INTUBATED
count              508.000000  508.000000  508.000000  508.000000
mean                 0.015748    0.066929    0.582677    0.029528
std                  0.124622    0.250146    0.493603    0.169447
min                  0.000000    0.000000    0.000000    0.000000
25%                  0.000000    0.000000    0.000000    0.000000
50%                  0.000000    0.000000    1.000000    0.000000
75%                  0.000000    0.000000    1.000000    0.000000
max                  1.000000    1.000000    1.000000    1.000000

In [27]:
from sklearn.preprocessing import StandardScaler
columns_to_standardize = ['age', 'height', 'weight', 'systolic_blood_pressure', 
                          'diastolic_blood_pressure', 'heart_rate', 'respiratory_rate', 
                          'oxygen_saturation', 'temperature', 'wbc', 'rbc', 
                          'hemoglobin', 'hematocrit', 'platelet_count', 'alt', 
                          'ast', 'serum_creatinine', 'sodium', 'potassium', 'lactate', 
                          'pao2', 'motor', 'verbal', 'eye', 'mcv', 'mch', 'mchc', 
                          'rdw', 'aptt_aptr', 'pt', 'total_serum_bilirubin', 
                          'ph', 'esr', 'inr', 'ferritin', 'd_dimer', 'crp']


scaler = StandardScaler()

df1[columns_to_standardize] = scaler.fit_transform(df1[columns_to_standardize])

print(df1[columns_to_standardize].head())

        age    height    weight  systolic_blood_pressure  \
0  0.486777  0.046033 -0.136901                -1.378253
1 -0.306970 -1.538752 -0.305780                -0.334198
2 -0.490142  0.046033 -0.136901                -0.924316
3  1.707926  1.942784 -0.708911                 1.617732
4  1.524754  0.046033 -0.136901                 0.074346

   diastolic_blood_pressure  heart_rate  respiratory_rate  oxygen_saturation  \
0                 -1.056722   -0.708594         -0.684234          -0.016469
1                  0.111621   -0.251350          1.549282          -0.836679
2                 -0.277826   -1.394461         -0.125855          -0.344553
3                 -0.355716   -0.308505         -1.242613           0.475657
4                  0.033732   -2.137484         -0.963423           0.311615

   temperature       wbc       rbc  hemoglobin  hematocrit  platelet_count  \
0    -0.278453  0.795470  1.401201    0.118025    0.213178       -1.052570
1     0.240835 -0.811605 -0.187661   -0.494346   -0.819869        0.052511
2     0.552408 -0.490190 -0.438534   -0.605686   -0.644446        0.185530
3    -0.278453 -0.758035 -0.619720    0.396375    0.641990       -1.359536
4     0.448550 -0.972312  0.035337   -0.160325    0.310636       -1.605110

        alt       ast  serum_creatinine    sodium  potassium   lactate  \
0  0.098287 -0.134444          0.548214 -0.063484   0.026926  0.047269
1  0.426627  0.136635         -0.716076  0.322741  -0.163049 -0.709029
2  0.076397  0.250773         -0.476297 -0.063484  -0.353024 -1.181715
3 -0.930514 -0.491127          0.341132 -0.063484  -2.062794  2.127088
4 -0.689731 -0.462592         -0.062133  1.288302  -0.163049  0.898104

       pao2     motor    verbal       eye       mcv       mch      mchc  \
0 -0.397027  0.187685 -1.071643  0.174891 -1.893218 -1.735600 -0.266595
1 -0.805472  0.187685  0.320671  0.174891 -1.009727 -0.493540  1.071355
2  0.530812  0.187685  0.320671 -2.998127 -0.275750 -0.245129  0.030727
3  0.530812  0.187685  0.320671  0.174891  2.225210  1.600217 -0.638248
4  0.530812  0.187685  0.320671  0.174891  0.322306 -0.351591 -1.455884

        rdw  aptt_aptr        pt  total_serum_bilirubin        ph  \
0  2.408266   2.495510 -0.120963              -0.057389 -0.488909
1  0.121539  -0.550006 -0.399669               0.333936 -0.156369
2 -0.782516   0.004448 -0.000633              -0.644377 -0.042058
3  1.716930   0.004448 -0.000633              -0.057389 -0.042058
4  1.929649   0.004448 -0.000633               1.703574 -0.042058

            esr       inr  ferritin   d_dimer       crp
0  2.340288e-15 -0.109399 -0.156456 -0.544593  2.232470
1  2.340288e-15 -0.294573 -0.262163  1.762216 -0.461246
2  2.340288e-15  0.000530 -0.023890 -0.028325 -0.175195
3  2.340288e-15  0.000530 -0.023890 -0.028325 -0.175195
4  2.340288e-15  0.000530 -0.023890 -0.028325 -0.175195

In [28]:
df1.head()

,id,age,height,weight,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,oxygen_saturation,temperature,motor,verbal,eye,wbc,rbc,hemoglobin,hematocrit,mcv,mch,mchc,rdw,platelet_count,aptt_aptr,pt,alt,ast,serum_creatinine,sodium,potassium,total_serum_bilirubin,lactate,pao2,pao2_fio2,ph,esr,inr,ferritin,d_dimer,crp,Asthma,Cancer [active only],Chronic cardiac disease (not hypertension),Chronic neurological disorder,Chronic pulmonary (lung) disease,Chronic renal,Dementia [any etiology],Diabetes,Hematological,History of cancer [now in remission],Hypertension,Kidney disease,Liver disease,Obesity,Other,Pregnancy,Rheumatologic disorder,Stroke,SEX,INTUBATED
0,1,0.486777,0.046033,-0.136901,-1.378253,-1.056722,-0.708594,-0.684234,-0.016469,-0.278453,0.187685,-1.071643,0.174891,0.795470,1.401201,0.118025,0.213178,-1.893218,-1.735600,-0.266595,2.408266,-1.052570,2.495510,-0.120963,0.098287,-0.134444,0.548214,-0.063484,0.026926,-0.057389,0.047269,-0.397027,1.5,-0.488909,2.340288e-15,-0.109399,-0.156456,-0.544593,2.232470,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0
1,2,-0.306970,-1.538752,-0.305780,-0.334198,0.111621,-0.251350,1.549282,-0.836679,0.240835,0.187685,0.320671,0.174891,-0.811605,-0.187661,-0.494346,-0.819869,-1.009727,-0.493540,1.071355,0.121539,0.052511,-0.550006,-0.399669,0.426627,0.136635,-0.716076,0.322741,-0.163049,0.333936,-0.709029,-0.805472,1.5,-0.156369,2.340288e-15,-0.294573,-0.262163,1.762216,-0.461246,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
2,3,-0.490142,0.046033,-0.136901,-0.924316,-0.277826,-1.394461,-0.125855,-0.344553,0.552408,0.187685,0.320671,-2.998127,-0.490190,-0.438534,-0.605686,-0.644446,-0.275750,-0.245129,0.030727,-0.782516,0.185530,0.004448,-0.000633,0.076397,0.250773,-0.476297,-0.063484,-0.353024,-0.644377,-1.181715,0.530812,1.5,-0.042058,2.340288e-15,0.000530,-0.023890,-0.028325,-0.175195,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,4,1.707926,1.942784,-0.708911,1.617732,-0.355716,-0.308505,-1.242613,0.475657,-0.278453,0.187685,0.320671,0.174891,-0.758035,-0.619720,0.396375,0.641990,2.225210,1.600217,-0.638248,1.716930,-1.359536,0.004448,-0.000633,-0.930514,-0.491127,0.341132,-0.063484,-2.062794,-0.057389,2.127088,0.530812,1.5,-0.042058,2.340288e-15,0.000530,-0.023890,-0.028325,-0.175195,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
4,5,1.524754,0.046033,-0.136901,0.074346,0.033732,-2.137484,-0.963423,0.311615,0.448550,0.187685,0.320671,0.174891,-0.972312,0.035337,-0.160325,0.310636,0.322306,-0.351591,-1.455884,1.929649,-1.605110,0.004448,-0.000633,-0.689731,-0.462592,-0.062133,1.288302,-0.163049,1.703574,0.898104,0.530812,1.5,-0.042058,2.340288e-15,0.000530,-0.023890,-0.028325,-0.175195,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0

In [29]:
df3.head()

   hospital_length_of_stay  parent_id
0                       21          1
1                        5          2
2                        7          3
3                        9          4
4                        9          5

Standardising HLOS column

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df3['hospital_length_of_stay_scaled'] = scaler.fit_transform(df3[['hospital_length_of_stay']])

print(df3[['hospital_length_of_stay', 'hospital_length_of_stay_scaled']].head())

   hospital_length_of_stay  hospital_length_of_stay_scaled
0                       21                        0.720477
1                        5                       -0.625120
2                        7                       -0.456920
3                        9                       -0.288721
4                        9                       -0.288721

Merging Data_at_admission(df1) and Hospital_Length_of_stay(df3) using parent_id

In [31]:

merged_df = pd.merge(df1, df3, left_on='id', right_on='parent_id', how='inner')

print(merged_df.head())

   id       age    height    weight  systolic_blood_pressure  \
0   1  0.486777  0.046033 -0.136901                -1.378253
1   2 -0.306970 -1.538752 -0.305780                -0.334198
2   3 -0.490142  0.046033 -0.136901                -0.924316
3   4  1.707926  1.942784 -0.708911                 1.617732
4   5  1.524754  0.046033 -0.136901                 0.074346

   diastolic_blood_pressure  heart_rate  respiratory_rate  oxygen_saturation  \
0                 -1.056722   -0.708594         -0.684234          -0.016469
1                  0.111621   -0.251350          1.549282          -0.836679
2                 -0.277826   -1.394461         -0.125855          -0.344553
3                 -0.355716   -0.308505         -1.242613           0.475657
4                  0.033732   -2.137484         -0.963423           0.311615

   temperature     motor    verbal       eye       wbc       rbc  hemoglobin  \
0    -0.278453  0.187685 -1.071643  0.174891  0.795470  1.401201    0.118025
1     0.240835  0.187685  0.320671  0.174891 -0.811605 -0.187661   -0.494346
2     0.552408  0.187685  0.320671 -2.998127 -0.490190 -0.438534   -0.605686
3    -0.278453  0.187685  0.320671  0.174891 -0.758035 -0.619720    0.396375
4     0.448550  0.187685  0.320671  0.174891 -0.972312  0.035337   -0.160325

   hematocrit       mcv       mch      mchc       rdw  platelet_count  \
0    0.213178 -1.893218 -1.735600 -0.266595  2.408266       -1.052570
1   -0.819869 -1.009727 -0.493540  1.071355  0.121539        0.052511
2   -0.644446 -0.275750 -0.245129  0.030727 -0.782516        0.185530
3    0.641990  2.225210  1.600217 -0.638248  1.716930       -1.359536
4    0.310636  0.322306 -0.351591 -1.455884  1.929649       -1.605110

   aptt_aptr        pt       alt       ast  serum_creatinine    sodium  \
0   2.495510 -0.120963  0.098287 -0.134444          0.548214 -0.063484
1  -0.550006 -0.399669  0.426627  0.136635         -0.716076  0.322741
2   0.004448 -0.000633  0.076397  0.250773         -0.476297 -0.063484
3   0.004448 -0.000633 -0.930514 -0.491127          0.341132 -0.063484
4   0.004448 -0.000633 -0.689731 -0.462592         -0.062133  1.288302

   potassium  total_serum_bilirubin   lactate      pao2  pao2_fio2        ph  \
0   0.026926              -0.057389  0.047269 -0.397027        1.5 -0.488909
1  -0.163049               0.333936 -0.709029 -0.805472        1.5 -0.156369
2  -0.353024              -0.644377 -1.181715  0.530812        1.5 -0.042058
3  -2.062794              -0.057389  2.127088  0.530812        1.5 -0.042058
4  -0.163049               1.703574  0.898104  0.530812        1.5 -0.042058

            esr       inr  ferritin   d_dimer       crp  Asthma  \
0  2.340288e-15 -0.109399 -0.156456 -0.544593  2.232470       0
1  2.340288e-15 -0.294573 -0.262163  1.762216 -0.461246       0
2  2.340288e-15  0.000530 -0.023890 -0.028325 -0.175195       0
3  2.340288e-15  0.000530 -0.023890 -0.028325 -0.175195       0
4  2.340288e-15  0.000530 -0.023890 -0.028325 -0.175195       0

   Cancer [active only]  Chronic cardiac disease (not hypertension)  \
0                     0                                           0
1                     0                                           0
2                     0                                           0
3                     0                                           0
4                     0                                           1

   Chronic neurological disorder  Chronic pulmonary (lung) disease  \
0                              0                                 0
1                              0                                 0
2                              0                                 0
3                              0                                 0
4                              0                                 0

   Chronic renal  Dementia [any etiology]  Diabetes  Hematological  \
0              0                        0         1              0
1              0                        0         0              0
2              0                        0         0              0
3              0                        0         0              0
4              0                        0         1              0

   History of cancer [now in remission]  Hypertension  Kidney disease  \
0                                     0             1               0
1                                     0             1               0
2                                     0             1               0
3                                     0             1               0
4                                     0             1               0

   Liver disease  Obesity  Other  Pregnancy  Rheumatologic disorder  Stroke  \
0              0        0      1          0                       0       0
1              0        0      1          0                       0       0
2              0        0      0          0                       0       0
3              0        0      1          0                       0       0
4              0        0      1          0                       0       0

   SEX  INTUBATED  hospital_length_of_stay  parent_id  \
0    1          0                       21          1
1    0          0                        5          2
2    0          0                        7          3
3    1          0                        9          4
4    1          0                        9          5

   hospital_length_of_stay_scaled
0                        0.720477
1                       -0.625120
2                       -0.456920
3                       -0.288721
4                       -0.288721

Splitting the dataset into 80%(train) and 20%(test)

In [32]:
from sklearn.model_selection import train_test_split

X = merged_df.drop(columns=['hospital_length_of_stay'])  # Features
y = merged_df['hospital_length_of_stay']  # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (406, 61)
Testing data shape: (102, 61)

Building MLP model

In [33]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

mlp = MLPRegressor(activation='relu', alpha=0.01, hidden_layer_sizes=(50,), learning_rate='constant', solver='adam', max_iter=1000, random_state=42)

mlp.fit(X_train_scaled, y_train)

y_pred = mlp.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse}")

r2 = r2_score(y_test, y_pred)
print(f"R-squared: {r2}")

Mean Squared Error (MSE): 11.010433212210343
R-squared: 0.9134211619975827

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

In [34]:

from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score

mlp = MLPRegressor(activation='tanh', alpha=0.01, hidden_layer_sizes=(50,), learning_rate='constant', solver='adam')

mlp.fit(X_train, y_train)

y_pred = mlp.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 99.9007699166874
R-squared: 0.2144457526574196

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Preprocesing Days-breakdown (df2) dataset

In [35]:
df2.head()

,id,parent_id,day,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,oxygen_saturation,temperature,highest_mean_arterial_pressure,lowest_mean_arterial_pressure,highest_heart_rate,lowest_heart_rate,highest_creatinine,lowest_urine_output,highest_gcs,lowest_gcs,intubated,highest_ph,lowest_ph,cardiac_arrest,arrested_time,major_cardiac_events,clinically_diagnosed_infections,mechanical_ventilation,number_of_vasoactive_agents,antiarrhythmic_therapies,renal_replacement_therapy_dialysis,cardiovascular_mechanical_support,fluid_balance,wbc,rbc,hemoglobin,hematocrit,platelet_count,aptt_aptr,pt,alt,ast,mch,mcv,mchc,rdw,serum_creatinine,sodium,potassium,total_serum_bilirubin,lactate,pao2,pao2_fio2,ph,high_sensitivity_cardiac_troponin,esr,inr,ferritin,d_dimer,crp,hs_crp,echocardiogram,ejection_fraction,wall_motion_abnormality,chest_x_ray,cxr_findings,chest_ct,chest_ct_findings,head_ct,head_ct_findings,antimicrobial,anticoagulation,steroid
0,1,1,1,119.0,54.0,79.0,18.0,94.0,37.2,85.0,85.0,80.0,73.0,102.0,700.0,15.0,15.0,No,NaN,NaN,No,NaN,No,Yes,No,NaN,No,No,No,-700.0,8.4,4.97,116.0,0.354,116.0,44.0,NaN,NaN,NaN,23.3,71.2,328.0,18.0,102.0,142.0,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,921.0,NaN,NaN,NaN,No,NaN,NaN,No,"""[\""Unilateral Consolidation\""]""",No,"""[\""Bilateral consolidation/infiltration\""]""",No,"""[]""",Yes,Yes,No
1,2,1,2,133.0,64.0,73.0,18.0,98.0,37.1,NaN,NaN,73.0,69.0,88.0,1351.0,14.0,13.0,No,NaN,NaN,No,NaN,No,Yes,No,NaN,No,No,No,-1301.0,5.2,4.99,115.0,0.359,117.0,NaN,NaN,NaN,NaN,23.0,71.9,320.0,18.4,88.0,144.0,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,"""[]""",No,"""[]""",No,"""[]""",Yes,Yes,Yes
2,3,1,3,140.0,74.0,70.0,20.0,95.0,37.5,NaN,NaN,72.0,65.0,73.0,1420.0,13.0,13.0,No,NaN,NaN,No,NaN,No,Yes,No,NaN,No,No,No,-1420.0,2.5,5.26,121.0,0.372,145.0,NaN,NaN,NaN,NaN,23.0,70.7,325.0,18.6,73.0,142.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,"""[]""",No,"""[]""",No,"""[]""",Yes,Yes,Yes
3,4,1,4,154.0,78.0,77.0,18.0,95.0,37.1,NaN,NaN,80.0,72.0,85.0,350.0,15.0,14.0,No,NaN,NaN,No,NaN,No,Yes,No,NaN,No,No,No,-350.0,6.9,5.38,124.0,0.383,218.0,NaN,NaN,NaN,NaN,23.0,71.2,324.0,18.5,85.0,141.0,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,"""[\""Unilateral Consolidation\""]""",No,"""[]""",No,"""[]""",Yes,Yes,Yes
4,5,1,5,155.0,61.0,64.0,16.0,92.0,36.7,NaN,NaN,77.0,64.0,NaN,NaN,10.0,10.0,No,NaN,NaN,No,NaN,No,Yes,No,NaN,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,"""[]""",No,"""[]""",No,"""[]""",Yes,Yes,Yes

In [36]:
df2.columns

Index(['id', 'parent_id', 'day', 'systolic_blood_pressure',
       'diastolic_blood_pressure', 'heart_rate', 'respiratory_rate',
       'oxygen_saturation', 'temperature', 'highest_mean_arterial_pressure',
       'lowest_mean_arterial_pressure', 'highest_heart_rate',
       'lowest_heart_rate', 'highest_creatinine', 'lowest_urine_output',
       'highest_gcs', 'lowest_gcs', 'intubated', 'highest_ph', 'lowest_ph',
       'cardiac_arrest', 'arrested_time', 'major_cardiac_events',
       'clinically_diagnosed_infections', 'mechanical_ventilation',
       'number_of_vasoactive_agents', 'antiarrhythmic_therapies',
       'renal_replacement_therapy_dialysis',
       'cardiovascular_mechanical_support', 'fluid_balance', 'wbc', 'rbc',
       'hemoglobin', 'hematocrit', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'mch', 'mcv', 'mchc', 'rdw', 'serum_creatinine', 'sodium',
       'potassium', 'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2',
       'ph', 'high_sensitivity_cardiac_troponin', 'esr', 'inr', 'ferritin',
       'd_dimer', 'crp', 'hs_crp', 'echocardiogram', 'ejection_fraction',
       'wall_motion_abnormality', 'chest_x_ray', 'cxr_findings', 'chest_ct',
       'chest_ct_findings', 'head_ct', 'head_ct_findings', 'antimicrobial',
       'anticoagulation', 'steroid'],
      dtype='object')

In [37]:
df2 = df2[['parent_id','day','systolic_blood_pressure','diastolic_blood_pressure','heart_rate',
        'respiratory_rate','oxygen_saturation','temperature','wbc', 'rbc',
       'hemoglobin', 'hematocrit', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'mch', 'mcv', 'mchc', 'rdw', 'serum_creatinine', 'sodium',
       'potassium', 'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2',
       'ph', 'high_sensitivity_cardiac_troponin', 'esr', 'inr', 'ferritin',
       'd_dimer', 'crp', 'hs_crp','intubated']]
df2.head()

,parent_id,day,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,oxygen_saturation,temperature,wbc,rbc,hemoglobin,hematocrit,platelet_count,aptt_aptr,pt,alt,ast,mch,mcv,mchc,rdw,serum_creatinine,sodium,potassium,total_serum_bilirubin,lactate,pao2,pao2_fio2,ph,high_sensitivity_cardiac_troponin,esr,inr,ferritin,d_dimer,crp,hs_crp,intubated
0,1,1,119.0,54.0,79.0,18.0,94.0,37.2,8.4,4.97,116.0,0.354,116.0,44.0,NaN,NaN,NaN,23.3,71.2,328.0,18.0,102.0,142.0,4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,921.0,NaN,NaN,NaN,No
1,1,2,133.0,64.0,73.0,18.0,98.0,37.1,5.2,4.99,115.0,0.359,117.0,NaN,NaN,NaN,NaN,23.0,71.9,320.0,18.4,88.0,144.0,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
2,1,3,140.0,74.0,70.0,20.0,95.0,37.5,2.5,5.26,121.0,0.372,145.0,NaN,NaN,NaN,NaN,23.0,70.7,325.0,18.6,73.0,142.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
3,1,4,154.0,78.0,77.0,18.0,95.0,37.1,6.9,5.38,124.0,0.383,218.0,NaN,NaN,NaN,NaN,23.0,71.2,324.0,18.5,85.0,141.0,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
4,1,5,155.0,61.0,64.0,16.0,92.0,36.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No

In [38]:
df2.shape

(4064, 37)

In [39]:
df2.dtypes

parent_id                              int64
day                                    int64
systolic_blood_pressure              float64
diastolic_blood_pressure             float64
heart_rate                           float64
respiratory_rate                     float64
oxygen_saturation                    float64
temperature                          float64
wbc                                  float64
rbc                                  float64
hemoglobin                           float64
hematocrit                           float64
platelet_count                       float64
aptt_aptr                            float64
pt                                   float64
alt                                  float64
ast                                  float64
mch                                  float64
mcv                                  float64
mchc                                 float64
rdw                                  float64
serum_creatinine                     float64
sodium                               float64
potassium                            float64
total_serum_bilirubin                float64
lactate                              float64
pao2                                 float64
pao2_fio2                            float64
ph                                   float64
high_sensitivity_cardiac_troponin    float64
esr                                  float64
inr                                  float64
ferritin                             float64
d_dimer                               object
crp                                  float64
hs_crp                               float64
intubated                             object
dtype: object

Converting data types

In [40]:
# Handling non-numeric values in the 'd_dimer' column, such as '>4000'
df2['d_dimer'] = pd.to_numeric(df2['d_dimer'].replace('>4000', 4000), errors='coerce')

# Converting 'intubated' column from category to the correct type
df2['intubated'] = df2['intubated'].astype('category')

print(df2.dtypes)

parent_id                               int64
day                                     int64
systolic_blood_pressure               float64
diastolic_blood_pressure              float64
heart_rate                            float64
respiratory_rate                      float64
oxygen_saturation                     float64
temperature                           float64
wbc                                   float64
rbc                                   float64
hemoglobin                            float64
hematocrit                            float64
platelet_count                        float64
aptt_aptr                             float64
pt                                    float64
alt                                   float64
ast                                   float64
mch                                   float64
mcv                                   float64
mchc                                  float64
rdw                                   float64
serum_creatinine                      float64
sodium                                float64
potassium                             float64
total_serum_bilirubin                 float64
lactate                               float64
pao2                                  float64
pao2_fio2                             float64
ph                                    float64
high_sensitivity_cardiac_troponin     float64
esr                                   float64
inr                                   float64
ferritin                              float64
d_dimer                               float64
crp                                   float64
hs_crp                                float64
intubated                            category
dtype: object

In [41]:
df2.isnull().sum()

parent_id                               0
day                                     0
systolic_blood_pressure               975
diastolic_blood_pressure              975
heart_rate                            958
respiratory_rate                      960
oxygen_saturation                     958
temperature                           962
wbc                                  2321
rbc                                  2321
hemoglobin                           2321
hematocrit                           2321
platelet_count                       2326
aptt_aptr                            3884
pt                                   3812
alt                                  3617
ast                                  3617
mch                                  2321
mcv                                  2321
mchc                                 2321
rdw                                  2321
serum_creatinine                     2050
sodium                               2415
potassium                            2364
total_serum_bilirubin                3615
lactate                              3876
pao2                                 3742
pao2_fio2                            3796
ph                                   3748
high_sensitivity_cardiac_troponin    4064
esr                                  4055
inr                                  3812
ferritin                             3958
d_dimer                              3765
crp                                  3787
hs_crp                               4064
intubated                               0
dtype: int64

Dropping Columns with 100% Null values

In [42]:

df2 = df2.drop(['high_sensitivity_cardiac_troponin', 'hs_crp'], axis=1)

print(df2.head())

   parent_id  day  systolic_blood_pressure  diastolic_blood_pressure  \
0          1    1                    119.0                      54.0
1          1    2                    133.0                      64.0
2          1    3                    140.0                      74.0
3          1    4                    154.0                      78.0
4          1    5                    155.0                      61.0

   heart_rate  respiratory_rate  oxygen_saturation  temperature  wbc   rbc  \
0        79.0              18.0               94.0         37.2  8.4  4.97
1        73.0              18.0               98.0         37.1  5.2  4.99
2        70.0              20.0               95.0         37.5  2.5  5.26
3        77.0              18.0               95.0         37.1  6.9  5.38
4        64.0              16.0               92.0         36.7  NaN   NaN

   hemoglobin  hematocrit  platelet_count  aptt_aptr  pt  alt  ast   mch  \
0       116.0       0.354           116.0       44.0 NaN  NaN  NaN  23.3
1       115.0       0.359           117.0        NaN NaN  NaN  NaN  23.0
2       121.0       0.372           145.0        NaN NaN  NaN  NaN  23.0
3       124.0       0.383           218.0        NaN NaN  NaN  NaN  23.0
4         NaN         NaN             NaN        NaN NaN  NaN  NaN   NaN

    mcv   mchc   rdw  serum_creatinine  sodium  potassium  \
0  71.2  328.0  18.0             102.0   142.0        4.1
1  71.9  320.0  18.4              88.0   144.0        3.7
2  70.7  325.0  18.6              73.0   142.0        4.0
3  71.2  324.0  18.5              85.0   141.0        3.9
4   NaN    NaN   NaN               NaN     NaN        NaN

   total_serum_bilirubin  lactate  pao2  pao2_fio2  ph  esr  inr  ferritin  \
0                    NaN      NaN   NaN        NaN NaN  NaN  NaN     921.0
1                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN
2                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN
3                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN
4                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN

   d_dimer  crp intubated
0      NaN  NaN        No
1      NaN  NaN        No
2      NaN  NaN        No
3      NaN  NaN        No
4      NaN  NaN        No

Encoding Categorical Variables

In [43]:
from sklearn.preprocessing import OneHotEncoder
categorical_columns = ['intubated']
df2 = pd.get_dummies(df2, columns=categorical_columns)
print(df2.head())

   parent_id  day  systolic_blood_pressure  diastolic_blood_pressure  \
0          1    1                    119.0                      54.0
1          1    2                    133.0                      64.0
2          1    3                    140.0                      74.0
3          1    4                    154.0                      78.0
4          1    5                    155.0                      61.0

   heart_rate  respiratory_rate  oxygen_saturation  temperature  wbc   rbc  \
0        79.0              18.0               94.0         37.2  8.4  4.97
1        73.0              18.0               98.0         37.1  5.2  4.99
2        70.0              20.0               95.0         37.5  2.5  5.26
3        77.0              18.0               95.0         37.1  6.9  5.38
4        64.0              16.0               92.0         36.7  NaN   NaN

   hemoglobin  hematocrit  platelet_count  aptt_aptr  pt  alt  ast   mch  \
0       116.0       0.354           116.0       44.0 NaN  NaN  NaN  23.3
1       115.0       0.359           117.0        NaN NaN  NaN  NaN  23.0
2       121.0       0.372           145.0        NaN NaN  NaN  NaN  23.0
3       124.0       0.383           218.0        NaN NaN  NaN  NaN  23.0
4         NaN         NaN             NaN        NaN NaN  NaN  NaN   NaN

    mcv   mchc   rdw  serum_creatinine  sodium  potassium  \
0  71.2  328.0  18.0             102.0   142.0        4.1
1  71.9  320.0  18.4              88.0   144.0        3.7
2  70.7  325.0  18.6              73.0   142.0        4.0
3  71.2  324.0  18.5              85.0   141.0        3.9
4   NaN    NaN   NaN               NaN     NaN        NaN

   total_serum_bilirubin  lactate  pao2  pao2_fio2  ph  esr  inr  ferritin  \
0                    NaN      NaN   NaN        NaN NaN  NaN  NaN     921.0
1                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN
2                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN
3                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN
4                    NaN      NaN   NaN        NaN NaN  NaN  NaN       NaN

   d_dimer  crp  intubated_No  intubated_Yes
0      NaN  NaN          True          False
1      NaN  NaN          True          False
2      NaN  NaN          True          False
3      NaN  NaN          True          False
4      NaN  NaN          True          False

Imputing Categorical Columns

Handling Missing Values in Categorical Columns

In [44]:
knn_columns = ['systolic_blood_pressure','diastolic_blood_pressure','heart_rate',
        'respiratory_rate','oxygen_saturation','temperature','wbc', 'rbc',
       'hemoglobin', 'hematocrit', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
       'ast', 'mch', 'mcv', 'mchc', 'rdw', 'serum_creatinine', 'sodium',
       'potassium', 'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2',
       'ph', 'esr', 'inr', 'ferritin',
       'crp','d_dimer']

knn_imputer = KNNImputer(n_neighbors=5)

df2[knn_columns] = knn_imputer.fit_transform(df2[knn_columns])

print(df2.isnull().sum())

parent_id                   0
day                         0
systolic_blood_pressure     0
diastolic_blood_pressure    0
heart_rate                  0
respiratory_rate            0
oxygen_saturation           0
temperature                 0
wbc                         0
rbc                         0
hemoglobin                  0
hematocrit                  0
platelet_count              0
aptt_aptr                   0
pt                          0
alt                         0
ast                         0
mch                         0
mcv                         0
mchc                        0
rdw                         0
serum_creatinine            0
sodium                      0
potassium                   0
total_serum_bilirubin       0
lactate                     0
pao2                        0
pao2_fio2                   0
ph                          0
esr                         0
inr                         0
ferritin                    0
d_dimer                     0
crp                         0
intubated_No                0
intubated_Yes               0
dtype: int64

Standardising Numerical Columns

In [45]:
from sklearn.preprocessing import StandardScaler

numerical_columns = [
    'systolic_blood_pressure', 'diastolic_blood_pressure', 'heart_rate',
    'respiratory_rate', 'oxygen_saturation', 'temperature', 'wbc', 'rbc',
    'hemoglobin', 'hematocrit', 'platelet_count', 'aptt_aptr', 'pt', 'alt',
    'ast', 'mch', 'mcv', 'mchc', 'rdw', 'serum_creatinine', 'sodium',
    'potassium', 'total_serum_bilirubin', 'lactate', 'pao2', 'pao2_fio2',
    'ph', 'esr', 'inr', 'ferritin', 'd_dimer', 'crp'
]

scaler = StandardScaler()

df2[numerical_columns] = scaler.fit_transform(df2[numerical_columns])

print(df2[numerical_columns].head())

   systolic_blood_pressure  diastolic_blood_pressure  heart_rate  \
0                -0.463138                 -1.537887    0.017498
1                 0.313427                 -0.636899   -0.421890
2                 0.701710                  0.264089   -0.641584
3                 1.478275                  0.624485   -0.128965
4                 1.533744                 -0.907195   -1.080973

   respiratory_rate  oxygen_saturation  temperature       wbc       rbc  \
0         -0.723865          -0.019521     0.891124 -0.236414  1.171961
1         -0.723865           1.395861     0.668334 -1.236814  1.209716
2         -0.206818           0.334325     1.559493 -2.080900  1.719415
3         -0.723865           0.334325     0.668334 -0.705352  1.945948
4         -1.240912          -0.727211    -0.222826 -0.123870 -0.655405

   hemoglobin  hematocrit  platelet_count  aptt_aptr        pt       alt  \
0   -0.479988   -0.561403       -1.919562   0.468087  1.474395 -0.235853
1   -0.554697   -0.432943       -1.907696   1.494874  1.212107 -0.187552
2   -0.106445   -0.098946       -1.575455  -0.139603  1.754405 -0.321090
3    0.117680    0.183667       -0.709256  -0.349151  2.080493 -0.079585
4   -1.077657   -1.044415       -0.030535   0.971003  0.765508 -0.679086

        ast       mch       mcv      mchc       rdw  serum_creatinine  \
0  0.080278 -2.534973 -3.020296  0.264514  2.973109          0.030913
1 -0.324150 -2.685238 -2.886994 -0.589881  3.273886         -0.182087
2 -0.417479 -2.685238 -3.115512 -0.055884  3.424274         -0.410300
3 -0.166527 -2.685238 -3.020296 -0.162683  3.349080         -0.227729
4 -0.394665 -0.641639 -0.498976 -0.440362  1.333874          0.569497

     sodium  potassium  total_serum_bilirubin   lactate      pao2  pao2_fio2  \
0  0.997745   0.301397               0.115865 -0.407398  0.051103  -0.770068
1  1.566861  -0.820707               0.391127 -0.007414 -1.377432   1.193613
2  0.997745   0.020871              -0.709920 -0.807381 -0.683968   1.760232
3  0.713187  -0.259655              -0.365843 -0.451840 -1.169393  -0.114517
4  0.770099  -0.315760              -0.985182 -0.940709  0.786175   0.851388

         ph       esr       inr  ferritin   d_dimer       crp
0 -0.118339 -0.914383  1.463200 -0.423157  0.378662 -0.709993
1  0.664318 -1.328144  1.159294 -0.059242 -0.190899 -1.280778
2 -0.222693 -1.328144  1.706325  0.336090 -0.655729 -0.583026
3  1.551329  0.182082  2.010231 -1.514029  0.360968  0.903168
4  0.507787  0.347586  0.733825 -1.552864  0.735893 -0.395977

In [46]:
df2.shape

(4064, 36)

Merging Days-breakdown(df3) and HLOS(df2) data

In [47]:
df2['parent_id'] = df2['parent_id']  # if 'id' in df2 corresponds to 'parent_id' in df3
merged_df2 = pd.merge(df2, df3[['parent_id', 'hospital_length_of_stay']], on='parent_id')
merged_df2.head()

,parent_id,day,systolic_blood_pressure,diastolic_blood_pressure,heart_rate,respiratory_rate,oxygen_saturation,temperature,wbc,rbc,hemoglobin,hematocrit,platelet_count,aptt_aptr,pt,alt,ast,mch,mcv,mchc,rdw,serum_creatinine,sodium,potassium,total_serum_bilirubin,lactate,pao2,pao2_fio2,ph,esr,inr,ferritin,d_dimer,crp,intubated_No,intubated_Yes,hospital_length_of_stay
0,1,1,-0.463138,-1.537887,0.017498,-0.723865,-0.019521,0.891124,-0.236414,1.171961,-0.479988,-0.561403,-1.919562,0.468087,1.474395,-0.235853,0.080278,-2.534973,-3.020296,0.264514,2.973109,0.030913,0.997745,0.301397,0.115865,-0.407398,0.051103,-0.770068,-0.118339,-0.914383,1.463200,-0.423157,0.378662,-0.709993,True,False,21
1,1,2,0.313427,-0.636899,-0.421890,-0.723865,1.395861,0.668334,-1.236814,1.209716,-0.554697,-0.432943,-1.907696,1.494874,1.212107,-0.187552,-0.324150,-2.685238,-2.886994,-0.589881,3.273886,-0.182087,1.566861,-0.820707,0.391127,-0.007414,-1.377432,1.193613,0.664318,-1.328144,1.159294,-0.059242,-0.190899,-1.280778,True,False,21
2,1,3,0.701710,0.264089,-0.641584,-0.206818,0.334325,1.559493,-2.080900,1.719415,-0.106445,-0.098946,-1.575455,-0.139603,1.754405,-0.321090,-0.417479,-2.685238,-3.115512,-0.055884,3.424274,-0.410300,0.997745,0.020871,-0.709920,-0.807381,-0.683968,1.760232,-0.222693,-1.328144,1.706325,0.336090,-0.655729,-0.583026,True,False,21
3,1,4,1.478275,0.624485,-0.128965,-0.723865,0.334325,0.668334,-0.705352,1.945948,0.117680,0.183667,-0.709256,-0.349151,2.080493,-0.079585,-0.166527,-2.685238,-3.020296,-0.162683,3.349080,-0.227729,0.713187,-0.259655,-0.365843,-0.451840,-1.169393,-0.114517,1.551329,0.182082,2.010231,-1.514029,0.360968,0.903168,True,False,21
4,1,5,1.533744,-0.907195,-1.080973,-1.240912,-0.727211,-0.222826,-0.123870,-0.655405,-1.077657,-1.044415,-0.030535,0.971003,0.765508,-0.679086,-0.394665,-0.641639,-0.498976,-0.440362,1.333874,0.569497,0.770099,-0.315760,-0.985182,-0.940709,0.786175,0.851388,0.507787,0.347586,0.733825,-1.552864,0.735893,-0.395977,True,False,21

Creating Sequential data

In [48]:
n_patients_actual = len(merged_df2['parent_id'].unique())  # Count of unique patients
n_days_actual = len(merged_df2['day'].unique())  # Count of unique days

print(f"Actual number of patients: {n_patients_actual}")
print(f"Actual number of days: {n_days_actual}")

Actual number of patients: 508
Actual number of days: 8

In [50]:
import numpy as np
merged_df2 = merged_df2.reset_index(drop=True)

# Function to calculate remaining days for each patient
def calculate_remaining_days(group):
    group = group.sort_values(by='day') 
    group['remaining_days'] = group['hospital_length_of_stay'] - group['day']
    return group


merged_df2 = merged_df2.groupby('parent_id', as_index=False).apply(calculate_remaining_days)

# Dropping columns that are not needed for the RNN model
features = merged_df2.drop(columns=['parent_id', 'day', 'hospital_length_of_stay', 'remaining_days'])


sequences = merged_df2.groupby('parent_id').apply(lambda x: x[features.columns].values)
targets = merged_df2.groupby('parent_id')['remaining_days'].apply(lambda x: x.values)


X = np.array(list(sequences))
y = np.array(list(targets))

n_patients = X.shape[0]
n_days = X.shape[1]
n_features = X.shape[2]

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

Shape of X: (508, 8, 34)
Shape of y: (508, 8)

In [51]:
merged_df2.head()

     parent_id  day  systolic_blood_pressure  diastolic_blood_pressure  \
0 0          1    1                -0.463138                 -1.537887
  1          1    2                 0.313427                 -0.636899
  2          1    3                 0.701710                  0.264089
  3          1    4                 1.478275                  0.624485
  4          1    5                 1.533744                 -0.907195

     heart_rate  respiratory_rate  oxygen_saturation  temperature       wbc  \
0 0    0.017498         -0.723865          -0.019521     0.891124 -0.236414
  1   -0.421890         -0.723865           1.395861     0.668334 -1.236814
  2   -0.641584         -0.206818           0.334325     1.559493 -2.080900
  3   -0.128965         -0.723865           0.334325     0.668334 -0.705352
  4   -1.080973         -1.240912          -0.727211    -0.222826 -0.123870

          rbc  hemoglobin  hematocrit  platelet_count  aptt_aptr        pt  \
0 0  1.171961   -0.479988   -0.561403       -1.919562   0.468087  1.474395
  1  1.209716   -0.554697   -0.432943       -1.907696   1.494874  1.212107
  2  1.719415   -0.106445   -0.098946       -1.575455  -0.139603  1.754405
  3  1.945948    0.117680    0.183667       -0.709256  -0.349151  2.080493
  4 -0.655405   -1.077657   -1.044415       -0.030535   0.971003  0.765508

          alt       ast       mch       mcv      mchc       rdw  \
0 0 -0.235853  0.080278 -2.534973 -3.020296  0.264514  2.973109
  1 -0.187552 -0.324150 -2.685238 -2.886994 -0.589881  3.273886
  2 -0.321090 -0.417479 -2.685238 -3.115512 -0.055884  3.424274
  3 -0.079585 -0.166527 -2.685238 -3.020296 -0.162683  3.349080
  4 -0.679086 -0.394665 -0.641639 -0.498976 -0.440362  1.333874

     serum_creatinine    sodium  potassium  total_serum_bilirubin   lactate  \
0 0          0.030913  0.997745   0.301397               0.115865 -0.407398
  1         -0.182087  1.566861  -0.820707               0.391127 -0.007414
  2         -0.410300  0.997745   0.020871              -0.709920 -0.807381
  3         -0.227729  0.713187  -0.259655              -0.365843 -0.451840
  4          0.569497  0.770099  -0.315760              -0.985182 -0.940709

         pao2  pao2_fio2        ph       esr       inr  ferritin   d_dimer  \
0 0  0.051103  -0.770068 -0.118339 -0.914383  1.463200 -0.423157  0.378662
  1 -1.377432   1.193613  0.664318 -1.328144  1.159294 -0.059242 -0.190899
  2 -0.683968   1.760232 -0.222693 -1.328144  1.706325  0.336090 -0.655729
  3 -1.169393  -0.114517  1.551329  0.182082  2.010231 -1.514029  0.360968
  4  0.786175   0.851388  0.507787  0.347586  0.733825 -1.552864  0.735893

          crp  intubated_No  intubated_Yes  hospital_length_of_stay  \
0 0 -0.709993          True          False                       21
  1 -1.280778          True          False                       21
  2 -0.583026          True          False                       21
  3  0.903168          True          False                       21
  4 -0.395977          True          False                       21

     remaining_days
0 0              20
  1              19
  2              18
  3              17
  4              16

In [52]:
# Splitting the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)  
print("y_train shape:", y_train.shape)

X_train shape: (406, 8, 34)
y_train shape: (406, 8)

In [53]:
print("Data type of X:", X.dtype)
print("Data type of y:", y.dtype)

Data type of X: object
Data type of y: int64

In [54]:
# Converting X and y to numeric types (float32)
X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.float32)

In [55]:
import numpy as np

# Checking if there are any NaN values in X or y
print("NaN in X:", np.isnan(X).sum())
print("NaN in y:", np.isnan(y).sum())

NaN in X: 0
NaN in y: 0

Padding for unequal sequences

In [56]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

sequences = np.array(list(sequences))

n_features = sequences[0].shape[1] 
max_days = max([len(seq) for seq in sequences]) 

padded_sequences = pad_sequences(sequences, maxlen=max_days, dtype='float32', padding='post', value=0)

# Print the shape of the padded sequences
print(f"Shape of padded sequences: {padded_sequences.shape}")  # Should be (n_patients, max_days, n_features)

Shape of padded sequences: (508, 8, 34)

In [57]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Dropout

model = Sequential()

model.add(SimpleRNN(50, activation='relu', input_shape=(n_days, n_features)))

model.add(Dropout(0.2))

model.add(Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')

history = model.fit(X, y, epochs=100, batch_size=32, validation_split=0.2)

loss = model.evaluate(X, y)
print(f"Final Loss: {loss}")

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 202.6942 - val_loss: 90.8716
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 188.8162 - val_loss: 107.4843
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 150.3487 - val_loss: 90.9503
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 137.0704 - val_loss: 91.4303
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 98.9023 - val_loss: 89.0524
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.2645 - val_loss: 92.3548
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 108.0383 - val_loss: 89.2171
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 105.5557 - val_loss: 88.2986
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 107.9545 - val_loss: 84.6822
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 88.3231 - val_loss: 87.2557
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 88.4358 - val_loss: 85.1795
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 92.7411 - val_loss: 86.1474
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 90.3000 - val_loss: 74.7859
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 101.5387 - val_loss: 82.5147
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 80.0406 - val_loss: 81.0681
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.8519 - val_loss: 81.2783
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.4577 - val_loss: 83.4891
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 54.9750 - val_loss: 83.3339
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 56.0496 - val_loss: 74.8650
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 53.6032 - val_loss: 91.9811
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 58.8506 - val_loss: 88.1668
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52.9941 - val_loss: 84.7589
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.5819 - val_loss: 84.3645
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 50.8908 - val_loss: 82.7956
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.1995 - val_loss: 73.1100
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 48.1152 - val_loss: 80.2100
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42.1653 - val_loss: 85.4295
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39.3837 - val_loss: 69.6332
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42.0711 - val_loss: 84.0989
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 35.7840 - val_loss: 85.4286
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 33.5459 - val_loss: 79.0876
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 34.9845 - val_loss: 76.5970
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 33.9993 - val_loss: 94.5751
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 31.3568 - val_loss: 84.1998
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33.1788 - val_loss: 80.3575
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.3959 - val_loss: 81.7485
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 29.2933 - val_loss: 84.0159
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.5357 - val_loss: 89.5705
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.3989 - val_loss: 80.6774
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25.2604 - val_loss: 76.8737
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.8310 - val_loss: 89.2967
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.3943 - val_loss: 78.4133
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 26.7588 - val_loss: 74.2490
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.6994 - val_loss: 76.5357
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.6722 - val_loss: 95.5313
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.1012 - val_loss: 96.0637
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.8966 - val_loss: 92.0077
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.5809 - val_loss: 80.3833
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.5935 - val_loss: 90.5248
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.3986 - val_loss: 96.5845
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.8726 - val_loss: 92.3254
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 26.0649 - val_loss: 95.3795
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.6218 - val_loss: 102.8357
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33.5938 - val_loss: 93.1195
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.5489 - val_loss: 76.0950
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.7983 - val_loss: 91.4133
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.4001 - val_loss: 76.9498
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 24.6684 - val_loss: 84.7317
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.6057 - val_loss: 89.6522
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.0992 - val_loss: 84.6383
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.4387 - val_loss: 85.4418
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.9005 - val_loss: 93.2627
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.6925 - val_loss: 84.9995
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.4407 - val_loss: 74.3055
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.1561 - val_loss: 81.6672
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.8615 - val_loss: 85.5770
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.6326 - val_loss: 91.5626
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.9379 - val_loss: 93.7595
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20.3348 - val_loss: 79.4273
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.4135 - val_loss: 77.8937
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.6558 - val_loss: 87.2348
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.6660 - val_loss: 96.3791
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.9126 - val_loss: 80.1637
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.2681 - val_loss: 71.5528
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 26.1180 - val_loss: 79.1636
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.2236 - val_loss: 80.7429
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.1296 - val_loss: 84.2460
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.6141 - val_loss: 105.5134
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.2195 - val_loss: 87.3852
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.7778 - val_loss: 74.2266
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.3581 - val_loss: 90.8593
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.4619 - val_loss: 80.6382
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.6479 - val_loss: 76.2446
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.5786 - val_loss: 82.4543
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.6409 - val_loss: 71.3736
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.4038 - val_loss: 88.2574
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.8479 - val_loss: 84.1046
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.9916 - val_loss: 91.4870
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.5555 - val_loss: 76.8640
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.5914 - val_loss: 76.5581
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.2457 - val_loss: 90.3344
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.9693 - val_loss: 86.1078
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.7290 - val_loss: 86.3650
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.7375 - val_loss: 81.0954
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.6175 - val_loss: 88.2076
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.3401 - val_loss: 84.1037
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.8245 - val_loss: 91.1355
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.1251 - val_loss: 98.7601
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.0656 - val_loss: 70.3980
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.7677 - val_loss: 87.1949
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.2675
Final Loss: 30.54086685180664

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

def create_rnn_model(units=50, activation='relu', optimizer='adam', input_shape=(None, None)):
    model = Sequential()
    
    model.add(LSTM(units, activation=activation, input_shape=input_shape, return_sequences=False))
    
    model.add(Dense(1))
    
    model.compile(optimizer=optimizer, loss='mean_squared_error')
    
    return model

In [59]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

param_grid = {
    'units': [10, 50, 100],
    'activation': ['relu', 'tanh'],
    'optimizer': ['adam', 'rmsprop'],
    'batch_size': [32, 64],
    'epochs': [100, 200]
}

best_mse = float('inf')
best_params = None
best_model = None  

for units in param_grid['units']:
    for activation in param_grid['activation']:
        for optimizer in param_grid['optimizer']:
            for batch_size in param_grid['batch_size']:
                for epochs in param_grid['epochs']:
                    
                    model = create_rnn_model(units=units, activation=activation, optimizer=optimizer, input_shape=(X.shape[1], X.shape[2]))

                    early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

                    history = model.fit(X_train, y_train, 
                                        epochs=epochs, 
                                        batch_size=batch_size, 
                                        validation_data=(X_val, y_val), 
                                        callbacks=[early_stopping], 
                                        verbose=0)

                    
                    mse = model.evaluate(X_val, y_val, verbose=0)
                    if mse < best_mse:
                        best_mse = mse
                        best_params = {
                            'units': units, 
                            'activation': activation, 
                            'optimizer': optimizer, 
                            'batch_size': batch_size, 
                            'epochs': epochs
                        }
                        best_model = model


print("Best Hyperparameters:", best_params)
print("Best MSE on validation set:", best_mse)

In [60]:

best_model = create_rnn_model(units=best_params['units'], activation=best_params['activation'], optimizer=best_params['optimizer'], input_shape=(X.shape[1], X.shape[2]))

best_model.fit(X, y, epochs=best_params['epochs'], batch_size=best_params['batch_size'], verbose=1)

final_mse = best_model.evaluate(X, y)
print("Final MSE on training data:", final_mse)

Epoch 1/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 162.3633
Epoch 2/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 181.8839
Epoch 3/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 190.9799
Epoch 4/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 162.6936
Epoch 5/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 148.1724
Epoch 6/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 210.5768
Epoch 7/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 172.8440
Epoch 8/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.9960
Epoch 9/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 134.0832
Epoch 10/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 205.1453
Epoch 11/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 174.7288
Epoch 12/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 149.3880
Epoch 13/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 210.4109
Epoch 14/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 169.4389
Epoch 15/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 187.1878
Epoch 16/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 182.5727
Epoch 17/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 174.7515
Epoch 18/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 161.4052
Epoch 19/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 132.4425
Epoch 20/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 174.4788
Epoch 21/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 139.5675
Epoch 22/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126.3838
Epoch 23/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 150.3299
Epoch 24/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 156.4080
Epoch 25/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 133.7617
Epoch 26/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 163.7409
Epoch 27/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 136.9254
Epoch 28/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 144.8553
Epoch 29/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 142.2781
Epoch 30/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 155.6872
Epoch 31/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 132.5491
Epoch 32/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 160.0542
Epoch 33/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 156.0240
Epoch 34/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 184.6253
Epoch 35/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.8757
Epoch 36/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 142.4552
Epoch 37/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.0224
Epoch 38/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 137.9415
Epoch 39/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 151.7912
Epoch 40/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 137.3481
Epoch 41/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 92.3139
Epoch 42/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 89.2123
Epoch 43/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 103.5349
Epoch 44/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 116.8464
Epoch 45/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 145.8745
Epoch 46/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 123.6758
Epoch 47/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 109.0135
Epoch 48/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 100.0187
Epoch 49/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125.3091
Epoch 50/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 102.9757
Epoch 51/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107.9478
Epoch 52/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 100.9244
Epoch 53/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 93.1833
Epoch 54/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 103.7632
Epoch 55/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75.8141
Epoch 56/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 127.5931
Epoch 57/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 92.3785
Epoch 58/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 81.5210
Epoch 59/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 107.8143
Epoch 60/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 88.9653
Epoch 61/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 126.9096
Epoch 62/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 103.0343
Epoch 63/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 98.2215
Epoch 64/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 106.2639
Epoch 65/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 106.7222
Epoch 66/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 106.6093
Epoch 67/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 97.4637
Epoch 68/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 105.7635
Epoch 69/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 92.8363
Epoch 70/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92.5148
Epoch 71/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90.2266
Epoch 72/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 89.4599
Epoch 73/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 109.5441
Epoch 74/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 102.7117
Epoch 75/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 93.0764
Epoch 76/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 90.6316
Epoch 77/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75.0732
Epoch 78/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 76.4778
Epoch 79/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 81.9619
Epoch 80/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 80.2696
Epoch 81/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92.8428
Epoch 82/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90.1769
Epoch 83/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 85.2560
Epoch 84/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 103.5717
Epoch 85/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 94.9347
Epoch 86/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 68.9434
Epoch 87/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 66.5859
Epoch 88/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 73.0694
Epoch 89/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 71.4742
Epoch 90/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 73.9210
Epoch 91/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 62.9173
Epoch 92/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 83.8258
Epoch 93/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 72.0351
Epoch 94/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 78.2808
Epoch 95/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 73.2575
Epoch 96/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 85.1870
Epoch 97/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 82.2448
Epoch 98/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 70.5672
Epoch 99/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 73.3764
Epoch 100/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 79.1474
Epoch 101/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 60.7636
Epoch 102/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 61.7544
Epoch 103/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 82.8141
Epoch 104/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57.5065
Epoch 105/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 65.5756
Epoch 106/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 71.8901
Epoch 107/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 60.7965
Epoch 108/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55.8312
Epoch 109/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 76.9130
Epoch 110/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63.0743
Epoch 111/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 62.7120
Epoch 112/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52.6952
Epoch 113/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 57.6787
Epoch 114/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 67.0868
Epoch 115/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 59.7585
Epoch 116/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 63.1253
Epoch 117/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98.1445
Epoch 118/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 73.6704
Epoch 119/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 69.4757
Epoch 120/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 74.6741
Epoch 121/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 59.2890
Epoch 122/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73.5316
Epoch 123/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 52.1436
Epoch 124/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 58.7038
Epoch 125/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55.1083
Epoch 126/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 58.5005
Epoch 127/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 60.3387
Epoch 128/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 59.9095
Epoch 129/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 63.5871
Epoch 130/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 51.7354
Epoch 131/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 57.8157
Epoch 132/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63.5439
Epoch 133/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45.0403
Epoch 134/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 43.8578
Epoch 135/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 66.9829
Epoch 136/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 70.8202
Epoch 137/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 44.9241
Epoch 138/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 46.6402
Epoch 139/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 59.0088
Epoch 140/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 42.9033
Epoch 141/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 65.5567
Epoch 142/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 44.4677
Epoch 143/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 58.4494
Epoch 144/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 62.6466
Epoch 145/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 40.2607
Epoch 146/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 59.7616
Epoch 147/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54.8584
Epoch 148/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 49.2789
Epoch 149/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53.8224
Epoch 150/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 45.7584
Epoch 151/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52.4647
Epoch 152/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57.0831
Epoch 153/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 48.1303
Epoch 154/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 43.3422
Epoch 155/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 57.2905
Epoch 156/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 53.5884
Epoch 157/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 46.6141
Epoch 158/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41.7126
Epoch 159/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.6883
Epoch 160/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 48.5936
Epoch 161/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 49.7449
Epoch 162/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 42.0584
Epoch 163/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 39.5979
Epoch 164/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 44.1426
Epoch 165/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 44.4182
Epoch 166/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 43.5393
Epoch 167/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45.3429
Epoch 168/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41.0789
Epoch 169/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 49.6041
Epoch 170/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 35.5251
Epoch 171/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 40.5621
Epoch 172/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 39.6882
Epoch 173/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42.3790
Epoch 174/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.7525
Epoch 175/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.5703
Epoch 176/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34.9772
Epoch 177/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34.4508
Epoch 178/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41.6745
Epoch 179/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35.5648
Epoch 180/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36.8303
Epoch 181/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 39.5735
Epoch 182/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38.3981
Epoch 183/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 42.3878
Epoch 184/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.8490
Epoch 185/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.3093
Epoch 186/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.6826
Epoch 187/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.4985
Epoch 188/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.6727
Epoch 189/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.4963
Epoch 190/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41.1842
Epoch 191/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 42.1213
Epoch 192/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36.6293
Epoch 193/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 37.1298
Epoch 194/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35.9860
Epoch 195/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36.0894
Epoch 196/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34.4320
Epoch 197/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.1067
Epoch 198/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33.4787
Epoch 199/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 35.5179
Epoch 200/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32.6644
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35.8645
Final MSE on training data: 33.93358612060547

In [62]:
# Flatten the 3D data (n_patients, n_days, n_features) into 2D (n_samples, n_features)
X_flattened = X.reshape((X.shape[0] * X.shape[1], X.shape[2]))
y_flattened = y.reshape((y.shape[0] * y.shape[1]))

# Now run the trials using the flattened data
def run_mlp_trials(X, y, n_trials=5, cv_folds=5):
    mlp_mse = []

    for trial in range(n_trials):
        print(f"Running MLP trial {trial + 1}...")

        # Split data into training and test sets
        X_train, X_test, y_train, y_test = train_test_split(X_flattened, y_flattened, test_size=0.2, random_state=trial)

        # Initialize the MLP Regressor
        mlp = MLPRegressor(hidden_layer_sizes=(50,), activation='relu', solver='adam', max_iter=500, random_state=trial)

        # Cross-validation to evaluate MSE
        cv_mse = cross_val_score(mlp, X_train, y_train, cv=cv_folds, scoring='neg_mean_squared_error')
        cv_mse = -cv_mse.mean()  # Convert from negative MSE to positive

        # Train and evaluate the model
        mlp.fit(X_train, y_train)
        y_pred = mlp.predict(X_test)
        mse = mean_squared_error(y_test, y_pred)
        mlp_mse.append(mse)

        print(f"Trial {trial + 1} - Cross-validated MSE: {cv_mse}, Test MSE: {mse}")

    avg_mlp_mse = np.mean(mlp_mse)
    std_mlp_mse = np.std(mlp_mse)

    print(f"Average MSE across {n_trials} trials for MLP: {avg_mlp_mse}")
    print(f"Standard Deviation of MSE across {n_trials} trials for MLP: {std_mlp_mse}")

    return avg_mlp_mse, std_mlp_mse

# Run 5 trials for MLP
avg_mlp_mse, std_mlp_mse = run_mlp_trials(X_flattened, y_flattened, n_trials=5)

Running MLP trial 1...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Trial 1 - Cross-validated MSE: 113.24721221923828, Test MSE: 113.04336547851562
Running MLP trial 2...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Trial 2 - Cross-validated MSE: 110.44615020751954, Test MSE: 122.69720458984375
Running MLP trial 3...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Trial 3 - Cross-validated MSE: 110.49891510009766, Test MSE: 118.98921203613281
Running MLP trial 4...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Trial 4 - Cross-validated MSE: 114.3352767944336, Test MSE: 115.89602661132812
Running MLP trial 5...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Trial 5 - Cross-validated MSE: 111.59115142822266, Test MSE: 121.90484619140625
Average MSE across 5 trials for MLP: 118.5061264038086
Standard Deviation of MSE across 5 trials for MLP: 3.6332955360412598

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

In [66]:
def run_rnn_trials(X, y, n_trials=5, cv_folds=5):
    rnn_mse = []

    for trial in range(n_trials):
        print(f"Running RNN trial {trial + 1}...")

        # Split data into training and test sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=trial)

        # Reshape y_train and y_test to match the RNN output shape if necessary
        y_train_reshaped = y_train.reshape((y_train.shape[0], y_train.shape[1], 1))
        y_test_reshaped = y_test.reshape((y_test.shape[0], y_test.shape[1], 1))

        # Create the RNN model
        rnn_model = Sequential()
        rnn_model.add(LSTM(units=50, activation='tanh', input_shape=(X_train.shape[1], X_train.shape[2])))
        rnn_model.add(Dense(1))
        rnn_model.compile(optimizer='adam', loss='mean_squared_error')

        # Train the RNN model
        rnn_model.fit(X_train, y_train_reshaped, epochs=100, batch_size=32, verbose=0)

        # Predict on the test set
        y_pred = rnn_model.predict(X_test)

        # Check shapes before flattening
        print(f"y_test shape: {y_test.shape}, y_pred shape: {y_pred.shape}")

        # If shapes mismatch, truncate or pad y_pred
        if y_test.shape[1] > y_pred.shape[1]:
            y_test = y_test[:, :y_pred.shape[1]]  # Truncate y_test to match y_pred
        elif y_test.shape[1] < y_pred.shape[1]:
            y_pred = y_pred[:, :y_test.shape[1]]  # Truncate y_pred to match y_test

        # Ensure both y_test and y_pred are flattened properly for MSE calculation
        mse = mean_squared_error(y_test.flatten(), y_pred.flatten())
        rnn_mse.append(mse)

        print(f"Trial {trial + 1} - MSE for RNN: {mse}")

    avg_rnn_mse = np.mean(rnn_mse)
    std_rnn_mse = np.std(rnn_mse)

    print(f"Average MSE across {n_trials} trials for RNN: {avg_rnn_mse}")
    print(f"Standard Deviation of MSE across {n_trials} trials for RNN: {std_rnn_mse}")

    return avg_rnn_mse, std_rnn_mse

# Run 5 trials for RNN
avg_rnn_mse, std_rnn_mse = run_rnn_trials(X, y, n_trials=5)

Running RNN trial 1...
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
y_test shape: (102, 8), y_pred shape: (102, 1)
Trial 1 - MSE for RNN: 118.35525512695312
Running RNN trial 2...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
y_test shape: (102, 8), y_pred shape: (102, 1)
Trial 2 - MSE for RNN: 153.98391723632812
Running RNN trial 3...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
y_test shape: (102, 8), y_pred shape: (102, 1)
Trial 3 - MSE for RNN: 111.93910217285156
Running RNN trial 4...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
y_test shape: (102, 8), y_pred shape: (102, 1)
Trial 4 - MSE for RNN: 137.51364135742188
Running RNN trial 5...

c:\Users\cntej\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
y_test shape: (102, 8), y_pred shape: (102, 1)
Trial 5 - MSE for RNN: 118.88886260986328
Average MSE across 5 trials for RNN: 128.13613891601562
Standard Deviation of MSE across 5 trials for RNN: 15.48913860321045